image: node:16

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run build
    - mv dist public
  artifacts:
    paths:
      - public

deploy:
  stage: deploy
  script:
    - echo "Deployment to GitLab Pages"
  only:
    - main
